#!/usr/bin/env python3
"""
gen_instimg.py -- turn the boot sector + flat kernel image into kernel/instimg.c

The installer needs a byte-exact, bootable copy of the OS inside the running
kernel, so it can write it to a hard disk.  This script embeds those two blobs
as C arrays.

Usage: python tools/gen_instimg.py <boot.bin> <kernel.bin> [out.c] [load_addr]
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def emit(f, name, blob):
    f.write("const u8 %s[] = {\n" % name)
    for i in range(0, len(blob), 16):
        f.write("    " + ",".join("0x%02X" % b for b in blob[i:i + 16]) + ",\n")
    f.write("};\n")
    f.write("const u32 %s_len = %du;\n\n" % (name, len(blob)))


KSCN = b'KSCN'


def patch_boot(boot, kernel_len):
    """Write the kernel sector count into the boot sector's 'KSCN' field.

    boot.asm ships `dw 0` there and falls back to a hardcoded maximum if the
    field is zero.  Patching it means the boot sector never reads past the end
    of a small disk (e.g. the 566-sector install medium), which the BIOS would
    otherwise report as a read error.
    """
    sectors = (kernel_len + 511) // 512
    i = boot.find(KSCN)
    if i < 0 or i + 6 > len(boot):
        print("!! 'KSCN' marker not found in the boot sector - kernel length left at 0")
        return boot
    b = bytearray(boot)
    b[i + 4] = sectors & 0xFF
    b[i + 5] = (sectors >> 8) & 0xFF
    return bytes(b)


def main():
    if len(sys.argv) >= 2 and sys.argv[1] == "--patch":
        # 只生成"打了扇区数补丁的引导扇区"，不生成 C 数组。
        # 安装介质自己也是一块可引导盘：它必须携带最终内核（那颗内核里
        # 才有内嵌的可写盘镜像），而最终内核比载荷内核大，扇区数不一样，
        # 所以引导扇区要按介质的内核重新打一次补丁。
        if len(sys.argv) < 5:
            print("usage: gen_instimg.py --patch <boot.bin> <kernel.bin> <out_boot.bin>")
            return 1
        boot = open(sys.argv[2], "rb").read()[:512]
        kern_len = os.path.getsize(sys.argv[3])
        out = patch_boot(boot, kern_len)
        open(sys.argv[4], "wb").write(out)
        sectors = (kern_len + 511) // 512
        print("  media boot sector: %d kernel sectors (LBA 1..%d) -> %s"
              % (sectors, sectors, sys.argv[4]))
        if 1 + sectors > 2048:
            print("  !! media kernel would overlap the filesystem at LBA 2048")
            return 2
        return 0

    if len(sys.argv) < 3:
        print(__doc__)
        return 1
    boot_path, kern_path = sys.argv[1], sys.argv[2]
    out = sys.argv[3] if len(sys.argv) > 3 else os.path.join(ROOT, "kernel", "instimg.c")
    load = int(sys.argv[4], 0) if len(sys.argv) > 4 else 0x100000

    boot = open(boot_path, "rb").read()
    kern = open(kern_path, "rb").read()
    if len(boot) < 512:
        boot = boot + b"\x00" * (512 - len(boot))
    boot = boot[:512]
    if boot[510] != 0x55 or boot[511] != 0xAA:
        print("!! boot sector is missing the 0xAA55 signature")

    boot_patched = patch_boot(boot, len(kern))
    # the patched sector is also what goes into tinyos.img
    patched_path = os.path.join(os.path.dirname(os.path.abspath(boot_path)), "boot_patched.bin")
    with open(patched_path, "wb") as g:
        g.write(boot_patched)

    with open(out, "w", encoding="utf-8") as f:
        f.write("/* AUTO-GENERATED by tools/gen_instimg.py -- do not edit by hand.\n")
        f.write(" *\n")
        f.write(" * Embedded installer payload: the boot sector and a flat, bootable\n")
        f.write(" * kernel image.  `install` writes these to a hard disk so the machine\n")
        f.write(" * can boot TinyOS without a Multiboot loader.\n")
        f.write(" *\n")
        f.write(" * source: boot sector %d bytes, kernel image %d bytes (load 0x%X)\n"
                % (len(boot_patched), len(kern), load))
        f.write(" */\n")
        f.write("#include \"types.h\"\n\n")
        emit(f, "boot_img", boot_patched)
        emit(f, "kernel_img", kern)
        f.write("const u32 kernel_img_load = 0x%08Xu;\n" % load)

    sectors = (len(kern) + 511) // 512
    print("  instimg.c: boot=%d bytes kernel=%d bytes (%d sectors, needs LBA < %d)"
          % (len(boot_patched), len(kern), sectors, 1 + sectors))
    print("  patched boot sector -> %s" % patched_path)
    if 1 + sectors > 2048:
        print("  !! kernel image would overlap the filesystem at LBA 2048")
        return 2
    return 0


if __name__ == '__main__':
    sys.exit(main())
